<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>

    <!--
      Resources are compiled automatically on build.
    -->
    <Win32Resource>Resources/Resources.res</Win32Resource>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="CompileResources" BeforeTargets="BeforeBuild">
    <Exec Command="dotnet run --file &quot;$(ProjectDir)Resources/CompileResources.csx&quot; -- &quot;$(ProjectDir)Resources&quot;" />
  </Target>
</Project>
