name: main

on:
  workflow_dispatch:
    inputs:
      package-version:
        type: string
        description: Package version
        required: false
      deploy:
        type: boolean
        description: Deploy package
        required: false
        default: false
  push:
    branches:
      - prime
    tags:
      - "*"
  pull_request:
    branches:
      - prime

jobs:
  # This test job is defined locally (instead of relying on the one in the reusable nuget.yml workflow)
  # because we need to install mingw-w64 on Linux and macOS for resource compilation.
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    permissions:
      contents: read

    env:
      # Secrets can't be referenced in conditionals, but environment variables can.
      # https://github.com/github/docs/issues/6861#issuecomment-870757186
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

      - name: Install windres (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install -y mingw-w64

      - name: Install windres (macOS)
        if: runner.os == 'macOS'
        run: brew install mingw-w64

      - name: Run tests
        run: >
          dotnet test
          -p:CSharpier_Bypass=true
          --configuration Release
          --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
          --collect:"XPlat Code Coverage"
          --
          RunConfiguration.CollectSourceInformation=true
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Upload coverage
        if: ${{ env.CODECOV_TOKEN }}
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  main:
    needs: test
    uses: Tyrrrz/.github/.github/workflows/nuget.yml@prime
    permissions:
      actions: write
      contents: write
    with:
      windows-only: true
      skip-tests: true
      deploy: ${{ inputs.deploy || github.ref_type == 'tag' }}
      package-version: ${{ inputs.package-version || (github.ref_type == 'tag' && github.ref_name) || format('0.0.0-ci-{0}', github.sha) }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
